DATA.people.push(...[
  /* ---- Founding legend / Aeneid generation (mostly myth) ---- */
  {id:"aeneas", displayName:"Aeneas", fullName:"Aeneas", alternateNames:["Aeneas of Troy"], year:-1184, dynasty:"regal",
   role:"Trojan hero; legendary ancestor of the Romans", bio:"Legendary Trojan prince (son of Anchises and the goddess Venus) who escaped burning Troy carrying his father, led the Trojan refugees to Italy, married the Latin princess Lavinia, and founded Lavinium — the town whose dynasty (via Alba Longa) produced Romulus. Pure legend, canonized by Vergil's Aeneid.",
   njclNote:"The hero of the Aeneid — embodies pietas: carries Anchises and the household gods from Troy. Founds Lavinium, NOT Rome; his son founds Alba Longa, which leads to Romulus.",
   biologicalLinks:["anchises","ascanius-iulus"], maritalLinks:["creusa","lavinia"], adoptiveLinks:[], associateLinks:["evander"], powerLinks:["turnus","mezentius"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Aeneas","Vergil, Aeneid"]},
  {id:"anchises", displayName:"Anchises", fullName:"Anchises", alternateNames:[], year:-1184, dynasty:"regal",
   role:"Father of Aeneas; prophetic elder", bio:"Legendary Trojan elder loved by Venus. Aeneas famously carried him from burning Troy on his shoulder — the iconic image of Roman pietas. He died in Sicily and, in Aeneid Book 6, shows Aeneas a parade of unborn Roman heroes in the underworld.",
   njclNote:"Aeneid 6: he delivers Rome's mission statement — 'parcere subiectis et debellare superbos' (spare the humbled, crush the proud).",
   biologicalLinks:["aeneas"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Anchises","Vergil, Aeneid II, VI"]},
  {id:"creusa", displayName:"Creusa", fullName:"Creusa", alternateNames:[], year:-1184, dynasty:"regal",
   role:"First wife of Aeneas", bio:"Legendary daughter of King Priam and mother of Ascanius. Lost in the flight from burning Troy, she died; her ghost appeared to Aeneas and prophesied his destiny in 'Hesperia' (Italy).",
   njclNote:"Her death is why Aeneas needs a new Italian wife — setting up the Lavinia/Turnus conflict of the poem's second half.",
   biologicalLinks:["ascanius-iulus"], maritalLinks:["aeneas"], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Creusa","Vergil, Aeneid II"]},
  {id:"ascanius-iulus", displayName:"Ascanius (Iulus)", fullName:"Ascanius / Iulus", alternateNames:["Iulus","Ascanius"], year:-1170, dynasty:"regal",
   role:"Son of Aeneas; legendary founder of Alba Longa", bio:"Legendary son of Aeneas (by Creusa) who grew up on the flight to Italy and slew Numanus in the war against Turnus. After his father's death he founded Alba Longa on the Alban Mount, parent city of Rome itself. His alternate name 'Iulus' was claimed as the eponymous ancestor of the Julian gens.",
   njclNote:"Iulus → gens Julia: the genealogical trick that let Julius Caesar and Augustus claim descent from Aeneas and Venus.",
   biologicalLinks:["aeneas","creusa"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["foundational","myth","aeneid","dynasty"], sources:["Wikipedia: Ascanius","Livy I; Vergil, Aeneid"]},
  {id:"lavinia", displayName:"Lavinia", fullName:"Lavinia", alternateNames:[], year:-1170, dynasty:"regal",
   role:"Latinus' daughter; Aeneas' Italian wife", bio:"Legendary daughter of King Latinus whose marriage to the Trojan newcomer Aeneas — despite her betrothal to the Rutulian prince Turnus — sparked the war of the Aeneid's second half. The city of Lavinium was named for her.",
   njclNote:"Her contested hand is the 'Helen of Italy' plot engine: Aeneas vs. Turnus for Lavinia = Trojans vs. natives.",
   biologicalLinks:["latinus"], maritalLinks:["aeneas"], adoptiveLinks:[], associateLinks:[], powerLinks:["turnus"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Lavinia","Vergil, Aeneid VII–XII"]},
  {id:"latinus", displayName:"Latinus", fullName:"King Latinus", alternateNames:[], year:-1170, dynasty:"regal",
   role:"King of Latium", bio:"Legendary king of Laurentum/Latium, son of Faunus, who welcomed Aeneas, offered him his daughter Lavinia, and made the Trojan-Latin alliance that fused the two peoples. His wife Amata favored Turnus instead.",
   njclNote:"Namesake of the LATINS: his kingdom + the Trojan refugees become the Latin people; his city Lavinium's line runs to Alba Longa and Rome.",
   biologicalLinks:["lavinia"], maritalLinks:[], adoptiveLinks:[], associateLinks:["aeneas"], powerLinks:[],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Latinus","Vergil, Aeneid VII"]},
  {id:"evander", displayName:"Evander", fullName:"Evander of Pallantium", alternateNames:["Euander"], year:-1170, dynasty:"regal",
   role:"Arcadian king on the future Palatine", bio:"Legendary Arcadian king who founded Pallantium on the hill that would become Rome's Palatine. He received Aeneas as an ally, showed him the sites of future Rome, and gave him troops under his own son Pallas, whose death by Turnus fuels the poem's ending.",
   njclNote:"Aeneid 8's tour of proto-Rome: the Greek who explains the Palatine's shrines — and lends his doomed son.",
   biologicalLinks:["pallas"], maritalLinks:[], adoptiveLinks:[], associateLinks:["aeneas"], powerLinks:["mezentius"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Evander","Vergil, Aeneid VIII"]},
  {id:"pallas", displayName:"Pallas", fullName:"Pallas, son of Evander", alternateNames:[], year:-1170, dynasty:"regal",
   role:"Evander's son, killed by Turnus", bio:"Legendary young Arcadian prince entrusted by Evander to Aeneas as a pupil in war. Turnus killed him and stripped his baldric as a trophy — the sight of which at the poem's end drives Aeneas to kill the suppliant Turnus.",
   njclNote:"His belt-buckle is the poem's closing image: Aeneas sees it and kills Turnus 'immolat... poenam sumit' — the Aeneid ends on revenge.",
   biologicalLinks:["evander"], maritalLinks:[], adoptiveLinks:[], associateLinks:["aeneas"], powerLinks:["turnus"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Pallas (son of Evander)","Vergil, Aeneid X–XII"]},
  {id:"turnus", displayName:"Turnus", fullName:"Turnus, king of the Rutuli", alternateNames:[], year:-1170, dynasty:"regal",
   role:"Rutulian prince; Aeneas' rival", bio:"Legendary king of the Rutuli at Ardea, betrothed to Lavinia before Aeneas' arrival. He led the Italian resistance, killed Pallas, and was finally slain by Aeneas — the closing act of the Aeneid.",
   njclNote:"The 'Italian Achilles': Aeneas' final enemy. Remember: he kills Pallas, then dies for it under Aeneas' sword.",
   biologicalLinks:["juturna"], maritalLinks:[], adoptiveLinks:[], associateLinks:["mezentius"], powerLinks:["aeneas","pallas","evander"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Turnus","Vergil, Aeneid VII–XII"]},
  {id:"juturna", displayName:"Juturna", fullName:"Juturna", alternateNames:["Diuturna"], year:-1170, dynasty:"regal",
   role:"Nymph; sister of Turnus", bio:"Legendary fountain nymph, sister of Turnus, granted divinity by Jupiter. In Aeneid 12 she fights to save her doomed brother before withdrawing in grief. Her spring, the Lacus Juturnae in the Roman Forum, was a real landmark.",
   njclNote:"A myth bridge: her spring beside the Castor temple in the Forum was still shown to Romans as 'Juturna's'.",
   biologicalLinks:["turnus"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Juturna","Vergil, Aeneid XII"]},
  {id:"dido", displayName:"Dido", fullName:"Dido (Elissa)", alternateNames:["Elissa"], year:-760, dynasty:"regal",
   role:"Legendary founder and queen of Carthage", bio:"Legendary Phoenician princess who fled her brother Pygmalion of Tyre and founded Carthage (traditionally 814 or 760 BC). In Aeneid 1–4 she loves Aeneas, is abandoned on Jupiter's orders, and dies cursing his descendants — Vergil's aition for the Punic Wars.",
   njclNote:"Her dying curse (Aen. 4) is Vergil's explanation for Hannibal: 'let no love nor treaty be between our peoples.' Chronology is impossible — Vergil telescopes legend.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["aeneas"], powerLinks:["aeneas"],
   tags:["foundational","myth","aeneid"], sources:["Wikipedia: Dido","Vergil, Aeneid I–IV"]},
  {id:"mezentius", displayName:"Mezentius", fullName:"Mezentius of Caere", alternateNames:[], year:-1170, dynasty:"regal",
   role:"Etruscan tyrant; ally of Turnus", bio:"Legendary cruel king of the Etruscan city of Caere, expelled by his own people and sheltered by Turnus, whose cause he joined as chief warrior. Aeneas killed him after his son Lausus died shielding him.",
   njclNote:"'Contemptor divum' — despiser of the gods. His tyranny explains Etruscan Caere siding AGAINST him with Aeneas.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["turnus"], powerLinks:["aeneas","evander"],
   tags:["foundational","myth","aeneid","etruscan"], sources:["Wikipedia: Mezentius","Vergil, Aeneid VII–X"]},
  {id:"cacus", displayName:"Cacus", fullName:"Cacus", alternateNames:[], year:-1170, dynasty:"regal",
   role:"Fire-breathing monster slain by Hercules", bio:"Pure myth: a fire-breathing giant (or brigand) dwelling under the Aventine who stole Hercules' stolen-in-turn cattle of Geryon, dragging them backward by their tails. Hercules strangled him — founding the Ara Maxima cult on the future site of Rome.",
   njclNote:"Vergil Aen. 8 uses Evander to tell it: Rome's hearth-side story explaining the Ara Maxima and Greek-style Hercules worship at Rome.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["myth","aeneid","foundational"], sources:["Wikipedia: Cacus","Vergil, Aeneid VIII; Livy I"]},
  {id:"proca", displayName:"Proca", fullName:"Proca, king of Alba Longa", alternateNames:["Proca Silvius"], year:-800, dynasty:"regal",
   role:"King of Alba Longa; father of Numitor and Amulius", bio:"Legendary king of Alba Longa whose death set his sons against each other: the younger, Amulius, usurped the throne from the elder Numitor and made Numitor's daughter Rhea Silvia a Vestal — whose twins Romulus and Remus then founded Rome.",
   njclNote:"The father whose unclear succession produced the Amulius-vs-Numitor feud — the setup for the she-wolf story.",
   biologicalLinks:["numitor","amulius"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["foundational","myth","dynasty"], sources:["Wikipedia: Proca","Livy I"]},

  /* ---- Early Republic (regal → founding) ---- */
  {id:"titus-larcius", displayName:"Titus Larcius", fullName:"Titus Larcius Flavus", alternateNames:["Titus Lartius"], year:-501, dynasty:"foundingRepublic",
   role:"First Roman dictator (501 or 498 BC)", bio:"Consul in 501 BC and, by tradition, the first man to hold the dictatorship — created amid fears of Sabine war and Latium unrest after the kings' expulsion. His appointment fixed the office's pattern: six-month maximum term, one man's command in emergency.",
   njclNote:"FIRST dictator — know that the office existed from the early Republic and carried a 6-month limit. Lake Regillus era.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["aulus-postumius"], powerLinks:[],
   tags:["foundational","magistracy"], sources:["Wikipedia: Titus Larcius","Livy II"]},
  {id:"arruns-porsena", displayName:"Aruns (son of Porsena)", fullName:"Arruns, son of Lars Porsena", alternateNames:["Aruns"], year:-506, dynasty:"foundingRepublic",
   role:"Etruscan prince who fell at Aricia", bio:"Son of the Clusine king Lars Porsena. After his father made peace with Rome, Aruns led the Etruscan army south and besieged Aricia, where the Latins with Cumaean help under Aristodemus destroyed his force; Aruns himself died (c. 506 BC).",
   njclNote:"Porsena's son: his death at Aricia ends Etruscan expansion south — right after his father 'conquered' Rome.",
   biologicalLinks:["lars-porsena"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["etruscan","war"], sources:["Wikipedia: Aruns (son of Porsena)","Livy II; Dionysius"]},
  {id:"arruns-tarquinius", displayName:"Arruns Tarquinius", fullName:"Arruns Tarquinius", alternateNames:["Arruns, son of Superbus"], year:-509, dynasty:"foundingRepublic",
   role:"Son of Superbus; killed Brutus at Silva Arsia", bio:"Son of Tarquinius Superbus who fought for his father's restoration. At the Battle of Silva Arsia (509 BC) he and the consul Lucius Junius Brutus famously charged and killed each other — mutual spearing remembered as the duel that decided the Republic's birth-battle.",
   njclNote:"'Brutus and Arruns killed each other' is THE stock detail of Silva Arsia — the founder's death in victory.",
   biologicalLinks:["tarquinius-superbus","sextus-tarquinius","titus-tarquinius"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["lucius-junius-brutus"],
   tags:["dynasty","etruscan","war","foundational"], sources:["Wikipedia: Arruns Tarquinius (son of Tarquin the Proud)","Livy II"]},
  {id:"titus-tarquinius", displayName:"Titus Tarquinius", fullName:"Titus Tarquinius", alternateNames:["Titus, son of Superbus"], year:-496, dynasty:"foundingRepublic",
   role:"Son of Superbus; died at Lake Regillus", bio:"Son of Tarquinius Superbus who led the royalist cavalry at the Battle of Lake Regillus (c. 496 BC), where he killed the dictator Aulus Postumius' master of horse and was himself slain — the last great attempt to restore the monarchy.",
   njclNote:"Regillus (c. 496) ended Tarquin restoration hopes; Romans claimed Castor & Pollux fought for them — hence their Forum temple.",
   biologicalLinks:["tarquinius-superbus","sextus-tarquinius","arruns-tarquinius"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["aulus-postumius","octavius-mamilius"],
   tags:["dynasty","etruscan","war","foundational"], sources:["Wikipedia: Titus Tarquinius","Livy II"]},

  /* ---- Conflict of the Orders ---- */
  {id:"spurius-cassius", displayName:"Spurius Cassius", fullName:"Spurius Cassius Viscellinus", alternateNames:[], year:-485, dynasty:"foundingRepublic",
   role:"Thrice consul; executed for 'aiming at kingship'", bio:"Consul three times (502, 493, 486 BC), victor over the Aurunci and author of the foedus Cassianum treaty with the Latins. He then proposed Rome's first agrarian law to distribute conquered land — and was condemned and executed (485) on suspicion of seeking royal power.",
   njclNote:"First of the 'aimed at kingship' trio: Cassius (485), Maelius (439), Manlius Capitolinus (384). Land reform = regnum charge.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["agrarian","martyrdom","foundational"], sources:["Wikipedia: Spurius Cassius Viscellinus","Livy II"]},
  {id:"gaius-terentilius-harsa", displayName:"Gaius Terentilius", fullName:"Gaius Terentilius Harsa", alternateNames:["Terentilius"], year:-462, dynasty:"conflictOrders",
   role:"Tribune who demanded a written law code (462 BC)", bio:"Plebeian tribune whose rogatio Terentilia (462 BC) demanded that consular power be bound by a published, written law code. Nearly a decade of agitation followed, producing the decemviral commission and the Twelve Tables (451–450 BC).",
   njclNote:"The trigger for the Twelve Tables: Terentilius' demand that law be WRITTEN DOWN so patrician consuls couldn't twist it.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["appius-claudius-decemvir"], powerLinks:[],
   tags:["conflictOrders","law","foundational"], sources:["Wikipedia: Gaius Terentilius Harsa","Livy III"]},
  {id:"spurius-maelius", displayName:"Spurius Maelius", fullName:"Spurius Maelius", alternateNames:[], year:-439, dynasty:"conflictOrders",
   role:"Rich plebeian killed as a would-be king", bio:"A wealthy equestrian who, during the famine of 440–439 BC, bought grain from Etruria and Campania and distributed it to the starving plebs. Accused of courting the mob to seize kingship, he was killed in the Forum by Servilius Ahala on orders of the dictator Cincinnatus.",
   njclNote:"The bread-king: charity interpreted as a coup. His razed house-site was pointedly renamed the Aequimaelium ('levelled Maelius').",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["servilius-ahala","cincinnatus"],
   tags:["conflictOrders","tyranny","grain"], sources:["Wikipedia: Spurius Maelius","Livy IV"]},
  {id:"servilius-ahala", displayName:"Servilius Ahala", fullName:"Gaius Servilius Ahala", alternateNames:[], year:-439, dynasty:"conflictOrders",
   role:"Magister equitum who slew Maelius", bio:"Young noble who, as master of the horse under the dictator Cincinnatus (439 BC), killed the grain-distributing Spurius Maelius when he fled justice. Held up by the annalists as the model of a patriot who strikes down tyranny — and used later to excuse political murder.",
   njclNote:"'Ahala killed Maelius' is the canonical pairing — Cincinnatus dictator, Ahala his dagger-arm.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cincinnatus"], powerLinks:["spurius-maelius"],
   tags:["conflictOrders","tyranny"], sources:["Wikipedia: Gaius Servilius Ahala","Livy IV"]},
  {id:"marcus-valerius-corvus", displayName:"Valerius Corvus", fullName:"Marcus Valerius Corvus", alternateNames:["Corvus"], year:-348, dynasty:"conflictOrders",
   role:"Six-time consul; the 'raven' duelist", bio:"Young officer who, in single combat with a huge Gaul (349 BC), was aided — legend says — by a raven that perched on his helmet and pecked his foe, earning him the cognomen Corvus. Consul six times, he won the First Samnite War's key victory at Mount Gaurus (343).",
   njclNote:"The raven story = why 'Corvus.' Pair him with Manlius Torquatus as the two famous Gaul-slayers.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["war","legend","duel"], sources:["Wikipedia: Marcus Valerius Corvus","Livy VII–VIII"]},
  {id:"quintus-publilius-philo", displayName:"Publilius Philo", fullName:"Quintus Publilius Philo", alternateNames:[], year:-339, dynasty:"conflictOrders",
   role:"First plebeian dictator and praetor", bio:"Dominant plebeian statesman of the mid-4th century BC: consul four times, first plebeian dictator (339) and first plebeian praetor (337). His leges Publiliae (339) made plebiscites binding on all Romans, required one censor be plebeian, and forced patrum auctoritas to be given before the vote.",
   njclNote:"Lex Publiliae 339 — the law that made plebiscites bind the WHOLE state; a Conflict-of-Orders milestone between Licinio-Sextian (367) and Hortensian (287).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["conflictOrders","law","plebeian"], sources:["Wikipedia: Quintus Publilius Philo","Livy VIII"]},
  {id:"lucius-verginius", displayName:"Lucius Verginius", fullName:"Lucius Verginius", alternateNames:["Verginius"], year:-449, dynasty:"conflictOrders",
   role:"Centurion; father of Verginia", bio:"A centurion whose daughter Verginia was claimed as a slave by the decemvir Appius Claudius's client so the lustful Appius could seize her (449 BC). Verginius, unable to free her by law, stabbed her dead in the Forum — 'only thus can I make you free' — detonating the revolt that ended the decemvirate.",
   njclNote:"He kills his own daughter to save her from the decemvir — the parallell atrocity to Lucretia that brings down the second tyranny.",
   biologicalLinks:["verginia"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["appius-claudius-decemvir"],
   tags:["conflictOrders","foundational","martyrdom"], sources:["Wikipedia: Lucius Verginius","Livy III"]},

  /* ---- Punic & Macedonian wars era ---- */
  {id:"quintus-fabius-pictor", displayName:"Fabius Pictor", fullName:"Quintus Fabius Pictor", alternateNames:[], year:-216, dynasty:"punicWars",
   role:"The first Roman historian", bio:"Senator who fought in the Second Punic War and was sent to consult the Delphic oracle after Cannae (216 BC). He wrote the first Roman history — an annalistic account from Aeneas to his own day — composed, significantly, in Greek.",
   njclNote:"FIRST Roman historian — and he wrote in GREEK, not Latin. The annalistic tradition starts with him.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["fabius-maximus"], powerLinks:[],
   tags:["historian","punicWars"], sources:["Wikipedia: Quintus Fabius Pictor","Livy; Polybius"]},
  {id:"philopoemen", displayName:"Philopoemen", fullName:"Philopoemen of Megalopolis", alternateNames:[], year:-183, dynasty:"punicWars",
   role:"Achaean general; 'the last of the Greeks'", bio:"Eight-time strategos of the Achaean League and its greatest soldier, he crushed Nabis' Sparta and reorganized Achaean arms on Macedonian lines. Captured by the Messenians, he was executed by poison (183 BC); a Roman called him 'the last of the Greeks.'",
   njclNote:"'Last of the Greeks' — memorize the epithet; Plutarch pairs him with Flamininus.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["nabis","flamininus"],
   tags:["greek","general","punicWars"], sources:["Wikipedia: Philopoemen","Plutarch, Philopoemen"]},
  {id:"nabis", displayName:"Nabis", fullName:"Nabis of Sparta", alternateNames:[], year:-195, dynasty:"punicWars",
   role:"Tyrant of Sparta", bio:"Ruler of Sparta (207–192 BC) who built a reformist tyranny on freed helots and confiscated land. Defeated by Flamininus and the Achaeans in 195 and stripped of Argos; assassinated by Aetolian 'allies' he had summoned in 192.",
   njclNote:"Sparta's last strongman: Flamininus 'freed Greece' in 196 partly to destroy him, and the Achaeans finished the job.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["flamininus","philopoemen"],
   tags:["greek","tyranny","sparta"], sources:["Wikipedia: Nabis","Livy XXXIV–XXXV; Plutarch"]},
  {id:"andriscus", displayName:"Andriscus", fullName:"Andriscus (Pseudo-Philip)", alternateNames:["Pseudo-Philip","Pseudo-Perseus"], year:-148, dynasty:"punicWars",
   role:"Pretender who briefly refounded Macedon", bio:"An Adramyttian adventurer who claimed to be Philip, son of Perseus, and seized the Macedonian throne (150–149 BC), defeating Roman forces and sparking the Fourth Macedonian War. Quintus Caecilius Metellus crushed him at Pydna in 148; Macedonia was then made a Roman province.",
   njclNote:"The 'Pseudo-Philip': his fake-Perseus run is why Macedon finally becomes a PROVINCE in 148.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["perseus","scipio-aemilianus"],
   tags:["greek","pretender","macedon"], sources:["Wikipedia: Andriscus","Livy, Periochae; Diodorus"]},
  {id:"genthius", displayName:"Genthius", fullName:"Genthius of Illyria", alternateNames:["Genthios"], year:-168, dynasty:"punicWars",
   role:"Last king of Illyria", bio:"Illyrian king who allied with Perseus in the Third Macedonian War, arresting Roman envoys and raiding from his coasts. In 168 BC the praetor Lucius Anicius destroyed his kingdom in a month's campaign; the Romans split Illyria into four tribute-paying republics.",
   njclNote:"His fall (168) = Third Illyrian War, fought parallel to Pydna — the Adriatic's pirate kings ended for good.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["perseus"], powerLinks:[],
   tags:["illyria","war","punicWars"], sources:["Wikipedia: Gentius","Livy XLIV–XLV"]},
  {id:"prusias-ii", displayName:"Prusias II", fullName:"Prusias II of Bithynia", alternateNames:["Prusias the Hunter"], year:-183, dynasty:"punicWars",
   role:"King of Bithynia who betrayed Hannibal", bio:"King of Bithynia (182–149 BC) who sheltered the exiled Hannibal at his court and used him in his war on Eumenes II's Pergamum. When Flamininus demanded the fugitive, Prusias prepared to surrender him; Hannibal took poison rather than fall into Roman hands (c. 183 BC).",
   njclNote:"Hannibal's last host: his betrayal forces the great man's suicide — 'let us relieve Rome's anxiety, an old man at last.'",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["hannibal"], powerLinks:["hannibal","eumenes-ii"],
   tags:["greek","hannibal","east"], sources:["Wikipedia: Prusias II of Bithynia","Livy XXXIX; Plutarch, Flamininus"]},

  /* ---- Gracchan age & Jugurthine war ---- */
  {id:"bocchus-i", displayName:"Bocchus I", fullName:"Bocchus I of Mauretania", alternateNames:["Bocchus"], year:-105, dynasty:"gracchan",
   role:"King of Mauretania who betrayed Jugurtha", bio:"King of Mauretania and father-in-law of Jugurtha. After long vacillation between his son-in-law and Rome, he lured Jugurtha into a meeting and handed him bound to Sulla (105 BC), ending the Jugurthine War — and receiving western Numidia as reward.",
   njclNote:"Sulla's trophy-moment BEFORE fame: he negotiated the handover and later wore a signet of 'Jugurtha surrendered to Sulla' — infuriating Marius.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["sulla"], powerLinks:["jugurtha"],
   tags:["numidia","jugurtha","betrayal"], sources:["Wikipedia: Bocchus I","Sallust, Jugurtha; Plutarch, Sulla"]},
  {id:"adherbal", displayName:"Adherbal", fullName:"Adherbal of Numidia", alternateNames:[], year:-112, dynasty:"gracchan",
   role:"Co-heir of Numidia, murdered by Jugurtha", bio:"Son of Micipsa and co-heir of Numidia with Jugurtha and Hiempsal. Driven from the kingdom and besieged at Cirta (112 BC), he surrendered on promise of safety and was murdered by Jugurtha — whose massacre of Italian traders in the city forced Rome to declare war.",
   njclNote:"The Cirta massacre (112) — Italians killed WITH him — is the casus belli; Sallust makes his plea to the Senate a set-piece.",
   biologicalLinks:["micipsa"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["jugurtha"],
   tags:["numidia","jugurtha","martyrdom"], sources:["Wikipedia: Adherbal (king of Numidia)","Sallust, Jugurtha"]},
  {id:"memmius", displayName:"Gaius Memmius", fullName:"Gaius Memmius (tribune 111)", alternateNames:[], year:-111, dynasty:"gracchan",
   role:"Tribune who exposed Jugurthine corruption", bio:"Plebeian tribune of 111 BC who dragged Jugurtha's bribery of senators into the open and brought the king to Rome to testify — where a fellow tribune's veto silenced him and a lackey's murder went unpunished. Memmius was himself murdered in 99 as consular candidate by Saturninus' and Glaucia's gangs.",
   njclNote:"Jugurtha's verdict after Rome: 'a city for sale, doomed the day it finds a buyer.' Memmius is the man who proved him right.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["jugurtha","saturninus"],
   tags:["corruption","jugurtha","tribune"], sources:["Wikipedia: Gaius Memmius (proconsul of Macedonia)","Sallust, Jugurtha"]},
  {id:"metellus-numidicus", displayName:"Metellus Numidicus", fullName:"Quintus Caecilius Metellus Numidicus", alternateNames:["Numidicus"], year:-108, dynasty:"gracchan",
   role:"Consul who fought Jugurtha before Marius", bio:"Consul in 109 BC who reformed discipline, broke Jugurtha's open-field army at the Muthul (108), and earned the agnomen 'Numidicus' — only to be superseded by his own legate, Gaius Marius. Exiled in 100 for refusing to swear to Saturninus' agrarian law, recalled a year later amid popular repentance.",
   njclNote:"Agnomen = 'conqueror of Numidia' — but the credit was stolen by his subordinate Marius. The Metellus-Marius feud drives the 100s BC.",
   biologicalLinks:["metellus-pius"], maritalLinks:[], adoptiveLinks:[], associateLinks:["gaius-marius"], powerLinks:["jugurtha","saturninus"],
   tags:["numidia","metelli","marius"], sources:["Wikipedia: Quintus Caecilius Metellus Numidicus","Sallust, Jugurtha"]},
  {id:"divico", displayName:"Divico", fullName:"Divico of the Tigurini", alternateNames:[], year:-107, dynasty:"gracchan",
   role:"Helvetian chief; victor of the 'Tigurine yoke'", bio:"Leader of the Tigurini, a Helvetian pagus, who annihilated the consul Lucius Cassius Longinus' army at Agen (107 BC) and marched the survivors under the yoke — a humiliation Rome never forgot. Fifty years on, the aged Divico answered Caesar's demands with insult; Caesar crushed the Helvetii weeks later.",
   njclNote:"The 'Tigurine yoke' of 107 is the atrocity Caesar avenges in B.G. Book 1 — Divico himself delivers the taunt at the parley.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["julius-caesar"],
   tags:["gaul","helvetii","war"], sources:["Wikipedia: Divico","Caesar, B.G. 1.13–14; Orosius"]},

  /* ---- Marian & Sullan era ---- */
  {id:"rutilius-rufus", displayName:"Rutilius Rufus", fullName:"Publius Rutilius Rufus", alternateNames:[], year:-92, dynasty:"marianSullan",
   role:"Consul and martyr of the equestrian courts", bio:"Consul in 105 BC, mentor of Marius and military reformer who introduced gladiator training to legions. As legate in Asia he shielded provincials from tax-farmers — and the equestrian juries convicted him of extortion (92 BC) in retaliation. He spent his exile honored in the very Asia he was accused of fleecing.",
   njclNote:"'An innocent man condemned': Rutilius' conviction proves equestrian courts are as corrupt as senators — ammunition for Sulla's jury reform (81).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gaius-marius"], powerLinks:[],
   tags:["marius","corruption","exile"], sources:["Wikipedia: Publius Rutilius Rufus","Cicero; Tacitus"]},
  {id:"metellus-pius", displayName:"Metellus Pius", fullName:"Quintus Caecilius Metellus Pius", alternateNames:[], year:-80, dynasty:"marianSullan",
   role:"Sulla's colleague; commander against Sertorius", bio:"Son of Numidicus — his 'Pius' came from tearful pleading for his father's recall. Consul with Sulla in 80 BC and pontifex maximus, he led the Spanish war against Sertorius (79–72), grinding him down until Perperna's treachery finished it.",
   njclNote:"'Pius' = the son who wept for an exiled father. In Spain he was the slow half of the Metellus-Pompey pair against Sertorius.",
   biologicalLinks:["metellus-numidicus"], maritalLinks:[], adoptiveLinks:[], associateLinks:["sulla","pompey"], powerLinks:["sertorius"],
   tags:["metelli","sulla","sertorius"], sources:["Wikipedia: Quintus Caecilius Metellus Pius","Plutarch, Sertorius"]},
  {id:"gnaeus-papirius-carbo", displayName:"Papirius Carbo", fullName:"Gnaeus Papirius Carbo", alternateNames:["Carbo"], year:-82, dynasty:"marianSullan",
   role:"Marian consul crushed by Sulla", bio:"Three-time consul (85, 84, 82 BC) and Cinna's heir as leader of the Marian state. He commanded against Sulla's return in 82, lost the war at the Colline Gate, and fled to Sicily — where the 24-year-old Pompey captured and executed him on Sulla's behalf.",
   njclNote:"His execution earned Pompey the sneer 'adulescentulus carnifex' — 'teenage butcher.'",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cinna","gaius-norbanus"], powerLinks:["sulla","pompey"],
   tags:["marian","sulla","civilWar"], sources:["Wikipedia: Gnaeus Papirius Carbo (consul 85 BC)","Appian; Plutarch, Pompey"]},
  {id:"gaius-norbanus", displayName:"Gaius Norbanus", fullName:"Gaius Norbanus", alternateNames:["Norbanus"], year:-83, dynasty:"marianSullan",
   role:"Marian consul of 83 BC", bio:"Ex-tribune and consul in 83 BC who met Sulla's returning army first and was shattered at Mount Tifata near Capua. Proscribed, he fled to Rhodes and killed himself when the city prepared to surrender him.",
   njclNote:"First man beaten by Sulla's return — Mt. Tifata 83 opens the civil war's decisive year.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gnaeus-papirius-carbo"], powerLinks:["sulla"],
   tags:["marian","sulla","civilWar"], sources:["Wikipedia: Gaius Norbanus","Appian, Civil Wars I"]},
  {id:"fimbria", displayName:"Fimbria", fullName:"Gaius Flavius Fimbria", alternateNames:[], year:-85, dynasty:"marianSullan",
   role:"Marian killer who fought Mithridates", bio:"Marian legate who assassinated his own commander, the consul Lucius Valerius Flaccus, in Asia (86 BC) and took his army against Mithridates, sacking cities and burning Ilium. When Sulla crossed against him in 85, his legions deserted; he committed suicide at Pergamum.",
   njclNote:"Killed his own consul to take an army — the Marian side's most notorious internecine murder.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gaius-marius"], powerLinks:["sulla","mithridates"],
   tags:["marian","mithridates","murder"], sources:["Wikipedia: Gaius Flavius Fimbria","Appian, Mithridatica; Livy, Periochae"]},
  {id:"marcus-aquillius", displayName:"Marcus Aquillius", fullName:"Manius Aquillius (consul 101)", alternateNames:["Aquillius"], year:-88, dynasty:"marianSullan",
   role:"Victor of the Sicilian slave war; Mithridates' victim", bio:"Consul in 101 BC with Marius; he stamped out the Second Servile War in Sicily and triumphed. Sent to Asia in 90 to restore kings, he provoked war and in 88 was captured by Mithridates — who, legend says, executed him by pouring molten gold down his throat as a parable on Roman greed.",
   njclNote:"Molten gold = the greed parable (contrast Crassus' similar legendary death). He ended the SECOND Sicilian slave war (not Spartacus').",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gaius-marius"], powerLinks:["mithridates"],
   tags:["servileWar","mithridates","sicily"], sources:["Wikipedia: Manius Aquillius (consul 101 BC)","Appian, Mithridatica"]},
  {id:"hortensius", displayName:"Hortensius", fullName:"Quintus Hortensius Hortalus", alternateNames:["Hortensius Hortalus"], year:-70, dynasty:"marianSullan",
   role:"Leading orator before Cicero", bio:"The greatest courtroom orator of the generation before Cicero — known as 'the Dancer' for his florid gestures. Cicero defeated him in the Verres trial (70 BC) and supplanted him as Rome's top advocate; consul in 69, he later cooperated with Cicero and died in 50.",
   njclNote:"The rival Cicero beat on the Verres case — that 70 BC victory made Cicero the #1 orator.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cicero"], powerLinks:["cicero"],
   tags:["oratory","law","cicero"], sources:["Wikipedia: Quintus Hortensius","Cicero, Brutus"]},

  /* ---- First Triumvirate era ---- */
  {id:"gabinius", displayName:"Gabinius", fullName:"Aulus Gabinius", alternateNames:[], year:-58, dynasty:"firstTriumvirate",
   role:"Author of the lex Gabinia; consul 58 BC", bio:"As tribune in 67 BC he carried the lex Gabinia giving Pompey unprecedented command against the pirates. As consul in 58 he let Clodius send Cicero into exile. As proconsul of Syria he restored Ptolemy XII to Egypt without senatorial approval (55); tried for maiestas and bribery, he was exiled and died in 48.",
   njclNote:"Double-certamen figure: the 67 pirate law for Pompey AND the 58 consul who abandoned Cicero to Clodius.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["pompey","piso-caesoninus","ptolemy-xii"], powerLinks:["cicero"],
   tags:["pompey","cicero","law","exile"], sources:["Wikipedia: Aulus Gabinius","Cicero; Dio Cassius"]},
  {id:"piso-caesoninus", displayName:"Piso Caesoninus", fullName:"Lucius Calpurnius Piso Caesoninus", alternateNames:["Piso"], year:-58, dynasty:"firstTriumvirate",
   role:"Consul 58 BC; Caesar's father-in-law", bio:"Father of Calpurnia and so Caesar's father-in-law; consul with Gabinius in 58 BC while Clodius exiled Cicero, who never forgave him. Attacked in Cicero's savage speech In Pisonem (55). An Epicurean whose villa at Herculaneum held the Philodemus library; censor in 50.",
   njclNote:"Target of In Pisonem — and the Pompeii-papyri villa may be his. Also the father-in-law tie: Calpurnia → Caesar.",
   biologicalLinks:["calpurnia"], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","gabinius"], powerLinks:["cicero"],
   tags:["cicero","caesar","epicurean"], sources:["Wikipedia: Lucius Calpurnius Piso Caesoninus (consul 58 BC)","Cicero, In Pisonem"]},
  {id:"vatinius", displayName:"Vatinius", fullName:"Publius Vatinius", alternateNames:[], year:-59, dynasty:"firstTriumvirate",
   role:"Tribune of the lex Vatinia", bio:"Caesar's partisan: as tribune in 59 BC his lex Vatinia granted Caesar Cisalpine Gaul and Illyricum for five years — the command from which the Gallic conquest grew. Legate under Caesar, praetor 55, suffect consul for a few days in late 47.",
   njclNote:"Lex Vatinia 59 = Caesar's first Gallic provincia (Cisalpina + Illyricum; the Senate added Transalpine Gaul).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar"], powerLinks:["cicero"],
   tags:["caesar","law","gaul"], sources:["Wikipedia: Publius Vatinius","Caesar; Cicero"]},
  {id:"domitius-ahenobarbus", displayName:"Domitius Ahenobarbus", fullName:"Lucius Domitius Ahenobarbus (consul 54)", alternateNames:[], year:-54, dynasty:"firstTriumvirate",
   role:"Consul 54 BC; diehard anti-Caesar optimate", bio:"Fierce optimate who as consul in 54 BC swore to strip Caesar of his command. In 49 he took over the defense of Italy, was captured at Corfinium and released by Caesar, defended Massilia, and died fighting at Pharsalus (48) — the noblest optimate death of the war.",
   njclNote:"Ancestor of the emperor Nero through his son; Caesar spared him at Corfinium and he fought on anyway — died at Pharsalus.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cato-the-younger"], powerLinks:["julius-caesar"],
   tags:["optimate","pharsalus","caesar"], sources:["Wikipedia: Lucius Domitius Ahenobarbus (consul 54 BC)","Caesar, B.C.; Plutarch"]},
  {id:"ariovistus", displayName:"Ariovistus", fullName:"Ariovistus of the Suebi", alternateNames:[], year:-58, dynasty:"firstTriumvirate",
   role:"Germanic king defeated by Caesar", bio:"Suebi king who crossed the Rhine, crushed the Aedui at Magetobriga (c. 61 BC), and settled Germans in Gaul. Declared a 'friend of the Roman people' in 59, he was destroyed by Caesar at the Battle of the Vosges (58) — Caesar's first great Gallic victory — and died fleeing across the Rhine.",
   njclNote:"B.G. 1: Rome officially made him 'rex et amicus' — then Caesar beat him anyway. First battle of the Gallic War.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["julius-caesar"],
   tags:["gaul","germans","caesar"], sources:["Wikipedia: Ariovistus","Caesar, B.G. 1"]},
  {id:"orgetorix", displayName:"Orgetorix", fullName:"Orgetorix the Helvetian", alternateNames:[], year:-60, dynasty:"firstTriumvirate",
   role:"Helvetian noble whose plot triggered the Gallic War", bio:"Wealthy Helvetian noble who organized his people's mass migration through Roman Gaul (61 BC) and, per Caesar, schemed for kingship over Gaul. Tried for conspiracy, he died — probably suicide — before the migration began in 58, drawing Caesar into war.",
   njclNote:"B.G. 1's opening villain: his migration plan forces the Helvetian campaign that starts the whole Gallic War.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["julius-caesar"],
   tags:["gaul","helvetii","caesar"], sources:["Wikipedia: Orgetorix","Caesar, B.G. 1.2–4"]},
  {id:"ambiorix", displayName:"Ambiorix", fullName:"Ambiorix of the Eburones", alternateNames:[], year:-54, dynasty:"firstTriumvirate",
   role:"Eburones king; destroyer of Sabinus' legion", bio:"Co-king of the Eburones who in 54 BC annihilated the Roman winter camp of Sabinus and Cotta at Aduatuca — Caesar's worst Gallic disaster, a legion and a half lost. He then besieged Quintus Cicero's camp, was repulsed, and vanished into the Ardennes forests, never captured.",
   njclNote:"Aduatuca 54 = Caesar's biggest defeat in Gaul; Ambiorix disappears at the end — Rome never got him.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["julius-caesar","quintus-cicero"],
   tags:["gaul","revolt","caesar"], sources:["Wikipedia: Ambiorix","Caesar, B.G. 5–6"]},
  {id:"quintus-cicero", displayName:"Quintus Cicero", fullName:"Quintus Tullius Cicero", alternateNames:[], year:-54, dynasty:"firstTriumvirate",
   role:"Cicero's brother; Caesar's legate in Gaul", bio:"Younger brother of Marcus Cicero, praetor in 62 BC and a capable soldier. As Caesar's legate he held his winter camp against Ambiorix's siege (54 BC) — the set-piece of B.G. 5 — and later governed Asia. He was proscribed and killed with his brother in 43.",
   njclNote:"The siege of Q. Cicero's camp (B.G. 5.39–52) is the dramatic twin of Aduatuca — read him as the link between Cicero and Caesar.",
   biologicalLinks:["cicero"], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","pompey"], powerLinks:["ambiorix","mark-antony"],
   tags:["gaul","cicero","proscription"], sources:["Wikipedia: Quintus Tullius Cicero","Caesar, B.G. 5; Cicero"]},
  {id:"cornelia-metella", displayName:"Cornelia Metella", fullName:"Cornelia Metella", alternateNames:[], year:-52, dynasty:"firstTriumvirate",
   role:"Last wife of Pompey the Great", bio:"Highly educated daughter of Metellus Scipio — she read poetry and played the lyre, and Plutarch praises her mind. Widow of Publius Crassus (killed at Carrhae), she married Pompey in 52 BC and shared his flight after Pharsalus, sailing to Egypt as he was murdered.",
   njclNote:"Young scholar-bride of aging Pompey: daughter of Metellus Scipio, widow of Crassus' son — a dynastic knot at the war's heart.",
   biologicalLinks:["metellus-scipio"], maritalLinks:["pompey"], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["dynasty","pompey","women"], sources:["Wikipedia: Cornelia Metella","Plutarch, Pompey"]},
  {id:"atticus", displayName:"Atticus", fullName:"Titus Pomponius Atticus", alternateNames:["Pomponius Atticus"], year:-59, dynasty:"firstTriumvirate",
   role:"Cicero's dearest friend and publisher", bio:"Wealthy equestrian who lived for years in Athens (hence 'Atticus'), was Cicero's closest friend, banker, and publisher — recipient of the letters that are our richest source on the late Republic. A polite Epicurean who cultivated every faction and outlived them all, dying in 32 BC.",
   njclNote:"The man Cicero wrote his letters TO — Atticus preserved and published them. Neutrality as survival strategy.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cicero"], powerLinks:[],
   tags:["cicero","letters","equestrian"], sources:["Wikipedia: Titus Pomponius Atticus","Cornelius Nepos, Life of Atticus"]},
  {id:"ptolemy-xii", displayName:"Ptolemy XII Auletes", fullName:"Ptolemy XII Neos Dionysos 'Auletes'", alternateNames:["Auletes","the Flute-player"], year:-55, dynasty:"firstTriumvirate",
   role:"Father of Cleopatra; restored by Gabinius", bio:"King of Egypt (80–51 BC) nicknamed Auletes, 'the flute-player.' He bribed Caesar and Pompey for recognition (59), was expelled by his own Alexandrians, and was forcibly restored by Gabinius' army in 55 — an illegal intervention that exiled Gabinius. Father of Cleopatra and Ptolemy XIII.",
   njclNote:"The 10,000-talent bribe for recognition + Gabinius' unauthorized restoration = Egypt as a Roman protectorate in all but name.",
   biologicalLinks:["cleopatra","ptolemy-xiii"], maritalLinks:[], adoptiveLinks:[], associateLinks:["gabinius","pompey","julius-caesar"], powerLinks:[],
   tags:["egypt","ptolemy","client"], sources:["Wikipedia: Ptolemy XII Auletes","Dio Cassius; Strabo"]},
  {id:"catullus", displayName:"Catullus", fullName:"Gaius Valerius Catullus", alternateNames:[], year:-54, dynasty:"firstTriumvirate",
   role:"Neoteric poet who savaged Caesar", bio:"Brilliant young poet from Verona (c. 84–54 BC) of the 'new poets' school; his 116 poems range from the Lesbia cycle — addressed to Clodia, sister of Clodius — to vicious lampoons of Caesar and his creature Mamurra, for which Caesar nonetheless dined with Catullus' father.",
   njclNote:"'Lesbia' = Clodia Metelli. His obscene attacks on Caesar (poems 29, 57) are the era's famous literary enmity.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["clodius"], powerLinks:["julius-caesar"],
   tags:["poetry","literature","caesar"], sources:["Wikipedia: Catullus","Suetonius, Julius 73"]},

  /* ---- Caesar & the Liberators ---- */
  {id:"lentulus-crus", displayName:"Lentulus Crus", fullName:"Lucius Cornelius Lentulus Crus", alternateNames:[], year:-49, dynasty:"caesarLiberators",
   role:"Consul 49 BC who drove the crisis", bio:"Hardline consul of 49 BC who, with his colleague Claudius Marcellus, rammed through the senatus consultum ultimum against Caesar and rejected every compromise. He fled Italy ahead of Caesar, fought at Pharsalus, escaped to Egypt, and was executed there in 48.",
   njclNote:"The consul whose ultimatum pushed Caesar to the Rubicon — days later Caesar crossed, 'alea iacta est.'",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["pompey"], powerLinks:["julius-caesar"],
   tags:["optimate","civilWar","rubicon"], sources:["Wikipedia: Lucius Cornelius Lentulus Crus","Caesar, B.C.; Plutarch"]},
  {id:"curio", displayName:"Curio the Younger", fullName:"Gaius Scribonius Curio", alternateNames:["Curio"], year:-49, dynasty:"caesarLiberators",
   role:"Tribune 50 BC bought by Caesar", bio:"Brilliant, reckless tribune of 50 BC who started hostile to Caesar, was secretly bought by him (Caesar paid his enormous debts), then blocked the Senate by demanding both Pompey and Caesar disarm — popularly seen as fair. He fled to Caesar and died at the Bagradas (49) fighting Juba in Africa.",
   njclNote:"'Caesar bought Curio' — the famous purchase of a tribune; his even-handed-sounding veto paralyzed the Senate's response.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar"], powerLinks:["juba-i","pompey"],
   tags:["tribune","caesar","corruption"], sources:["Wikipedia: Gaius Scribonius Curio","Caesar, B.C.; Appian"]},
  {id:"trebonius", displayName:"Trebonius", fullName:"Gaius Trebonius", alternateNames:[], year:-44, dynasty:"caesarLiberators",
   role:"Caesar's legate turned assassin", bio:"Long-trusted legate of Caesar (siege of Massilia, 49 BC), raised to a suffect consulship in 45. Yet he had sounded Antony about a plot in 44, joined the conspiracy, and on the Ides detained Antony in conversation outside the Senate so he could not intervene. Dolabella had him killed at Smyrna in 43.",
   njclNote:"His Ides job: keep Antony OUTSIDE the door — the detail that lets the daggers work.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","brutus","cassius"], powerLinks:["mark-antony","dolabella"],
   tags:["assassin","ides","caesar"], sources:["Wikipedia: Gaius Trebonius","Cicero, Philippics; Appian"]},
  {id:"tillius-cimber", displayName:"Tillius Cimber", fullName:"Lucius Tillius Cimber", alternateNames:[], year:-44, dynasty:"caesarLiberators",
   role:"Conspirator who gave the signal", bio:"Praetor-designate who on the Ides petitioned Caesar to recall his exiled brother, surrounded his chair pressing the plea, and when Caesar waved him off seized Caesar's toga from his neck — the prearranged signal that loosed the daggers.",
   njclNote:"The petition for his brother was the cover: grabbing Caesar's toga = 'begin.' Casca then struck first.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["brutus","cassius","publius-casca"], powerLinks:["julius-caesar"],
   tags:["assassin","ides","caesar"], sources:["Wikipedia: Tillius Cimber","Plutarch, Caesar; Suetonius"]},
  {id:"publius-casca", displayName:"Casca", fullName:"Publius Servilius Casca Longus", alternateNames:["Casca"], year:-44, dynasty:"caesarLiberators",
   role:"The first to stab Caesar", bio:"Tribune of the plebs-elect who struck the first blow on the Ides — a dagger into Caesar's neck/shoulder from behind — as Caesar gasped 'Casca, what are you doing?' His brother Gaius Casca stabbed too. He died in the proscription-era fighting that followed.",
   njclNote:"FIRST dagger: Casca strikes, Caesar turns — 'villain Casca!' — and the rest fall on him. Both Casca brothers stabbed.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["brutus","cassius","tillius-cimber"], powerLinks:["julius-caesar"],
   tags:["assassin","ides","caesar"], sources:["Wikipedia: Servilius Casca","Plutarch, Caesar 66"]},
  {id:"gnaeus-pompey", displayName:"Gnaeus Pompey", fullName:"Gnaeus Pompeius (elder son)", alternateNames:["Gnaeus Pompeius"], year:-45, dynasty:"caesarLiberators",
   role:"Elder son of Pompey; died after Munda", bio:"Elder son of Pompey the Great who kept his father's cause alive in Spain with Sextus after Pharsalus. Defeated at Munda (45 BC) — the battle Caesar called his hardest — he was wounded, captured days later, and executed; his head was displayed at Hispalis.",
   njclNote:"Munda 45 = Caesar's last battle and near-defeat; Gnaeus' death leaves only Sextus to carry the Pompeian name.",
   biologicalLinks:["pompey","sextus-pompey"], maritalLinks:[], adoptiveLinks:[], associateLinks:["labienus"], powerLinks:["julius-caesar"],
   tags:["pompey","munda","civilWar"], sources:["Wikipedia: Gnaeus Pompeius (son of Pompey the Great)","Appian; Dio"]},
  {id:"sallust", displayName:"Sallust", fullName:"Gaius Sallustius Crispus", alternateNames:["Sallustius"], year:-45, dynasty:"caesarLiberators",
   role:"Historian of Catiline and Jugurtha", bio:"Populares tribune (52 BC), expelled from the Senate (50), restored by Caesar and made governor of Africa Nova, where he extorted a fortune. Retiring to his famous Gardens, he wrote the Bellum Catilinae and Bellum Jugurthinum — short, moralizing monographs that made him the canonical historian of this era.",
   njclNote:"THE source on Catiline & Jugurtha — certamen quotes his Jugurtha constantly ('urbem venalem'). Spare, Thucydidean style.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar"], powerLinks:[],
   tags:["historian","literature","catiline","jugurtha"], sources:["Wikipedia: Sallust","Bellum Catilinae; Bellum Jugurthinum"]},

  /* ---- Second Triumvirate era ---- */
  {id:"hirtius", displayName:"Aulus Hirtius", fullName:"Aulus Hirtius", alternateNames:[], year:-43, dynasty:"secondTriumvirate",
   role:"Consul 43 BC; killed at Mutina", bio:"Caesar's longtime officer who completed Book 8 of the Bellum Gallicum and probably wrote the Bellum Alexandrinum. Consul in 43 BC with Pansa, he led the senatorial army against Antony, won at Forum Gallorum and Mutina — and was killed breaking into Antony's camp.",
   njclNote:"Both consuls of 43 died at Mutina — the vacancy Octavian marched on Rome to fill (19 years old, first consul).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","pansa","octavian"], powerLinks:["mark-antony"],
   tags:["mutina","consul","caesar"], sources:["Wikipedia: Aulus Hirtius","Appian; Cassius Dio"]},
  {id:"pansa", displayName:"Vibius Pansa", fullName:"Gaius Vibius Pansa", alternateNames:["Pansa"], year:-43, dynasty:"secondTriumvirate",
   role:"Consul 43 BC; died of Mutina wounds", bio:"Caesarian moderate made consul for 43 BC with Hirtius. Leading the relief army to Mutina he was wounded at Forum Gallorum by Antony's ambush and died days later — gossip blamed his doctor or even Octavian. With both consuls dead, the way opened for Octavian's march on Rome.",
   njclNote:"Hirtius + Pansa both die at Mutina (April 43) — Cicero's quip: 'the war cost us two consuls.'",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["hirtius","octavian","cicero"], powerLinks:["mark-antony"],
   tags:["mutina","consul","caesar"], sources:["Wikipedia: Gaius Vibius Pansa Caetronianus","Appian"]},
  {id:"dolabella", displayName:"Dolabella", fullName:"Publius Cornelius Dolabella", alternateNames:[], year:-44, dynasty:"secondTriumvirate",
   role:"Suffect consul 44 BC; Cicero's ex-son-in-law", bio:"Young noble who married (and divorced) Cicero's daughter Tullia, became Antony's suffect colleague in 44 BC, and seized Syria by force — killing the conspirator Trebonius at Smyrna, for which the Senate declared him hostis. Besieged at Laodicea by Cassius, he had a soldier kill him (43).",
   njclNote:"Killed Trebonius — the first assassin to die — then was besieged by Cassius and killed himself in Syria.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["mark-antony"], powerLinks:["cassius","trebonius","cicero"],
   tags:["syria","triumvirate","civilWar"], sources:["Wikipedia: Publius Cornelius Dolabella (suffect consul 44 BC)","Appian"]},
  {id:"plancus", displayName:"Munatius Plancus", fullName:"Lucius Munatius Plancus", alternateNames:[], year:-43, dynasty:"secondTriumvirate",
   role:"Founder of Lugdunum; consummate survivor", bio:"Caesar's legate who founded the colonies of Lugdunum (Lyon) and Augusta Raurica in 43 BC, became consul (42), shifted through every faction — Cicero mocked his servility — abandoned Antony for Octavian, and in 27 BC formally proposed that Octavian take the name 'Augustus.'",
   njclNote:"Founder of Lyon AND the man who proposed 'Augustus' — the era's most adaptable careerist.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","mark-antony","octavian"], powerLinks:[],
   tags:["survivor","colonies","augustus"], sources:["Wikipedia: Lucius Munatius Plancus","Velleius; Cicero"]},
  {id:"pollio", displayName:"Asinius Pollio", fullName:"Gaius Asinius Pollio", alternateNames:[], year:-40, dynasty:"secondTriumvirate",
   role:"Historian and founder of Rome's first public library", bio:"Caesarian then Antonian officer, consul in 40 BC. Neutral after retirement, he wrote a (lost) history of the civil wars from 60 — the source behind much of Plutarch and Appian — patronized poets (he protected Vergil's confiscated farm), and founded Rome's first public library in the Atrium Libertatis.",
   njclNote:"First public library in Rome + the historian Horace warns ('full of danger') in Ode 2.1 — the civil wars' own chronicler.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["mark-antony","vergil","horace"], powerLinks:[],
   tags:["historian","literature","library"], sources:["Wikipedia: Gaius Asinius Pollio (consul 40 BC)","Horace, Odes 2.1"]},
  {id:"ventidius", displayName:"Ventidius", fullName:"Publius Ventidius Bassus", alternateNames:[], year:-38, dynasty:"secondTriumvirate",
   role:"Ex-muleteer who avenged Carrhae", bio:"Risen from supplying mule-teams — he had been displayed in Pompeius Strabo's triumph as a captive child — to suffect consul (43 BC) and Antony's eastern commander. In 39–38 he annihilated the invading Parthians at three battles and killed Pacorus at Gindarus, avenging Carrhae; he triumphed in 38.",
   njclNote:"The muleteer who beat the Parthians — the only Roman to take revenge for Carrhae before Antony's own failed expedition.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["mark-antony"], powerLinks:[],
   tags:["parthia","triumph","antony"], sources:["Wikipedia: Publius Ventidius Bassus","Dio; Gellius"]},
  {id:"atia", displayName:"Atia", fullName:"Atia Balba Caesonia", alternateNames:["Atia Balba"], year:-43, dynasty:"secondTriumvirate",
   role:"Mother of Octavian; niece of Caesar", bio:"Daughter of Julia — Julius Caesar's sister — making Caesar her uncle and Octavian his great-nephew, the blood claim on which the whole principate rests. Wife of M. Atius Balbus and then of the consul Philippus; she died in 43 BC, just as her son seized the consulship.",
   njclNote:"The Julius-Caesar blood link for Octavian: Caesar's sister Julia is HER mother — great-nephew = the adoption's legal basis.",
   biologicalLinks:["octavian"], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar"], powerLinks:[],
   tags:["dynasty","augustus","women"], sources:["Wikipedia: Atia Balba Caesonia","Suetonius, Augustus"]},
  {id:"balbus", displayName:"Cornelius Balbus", fullName:"Lucius Cornelius Balbus (the Elder)", alternateNames:["Balbus"], year:-40, dynasty:"secondTriumvirate",
   role:"Caesar's agent; first foreign-born consul", bio:"Wealthy man of Gades in Spain who became Caesar's confidential manager and fixer, handling his private affairs and intelligence. Naturalized by Pompey, defended by Cicero's speech Pro Balbo (56), he became in 40 BC the first foreign-born Roman consul — a landmark for provincial careers.",
   njclNote:"Pro Balbo is the speech defending his citizenship; 40 BC = first non-Roman-born consul — Spain enters the fastigium.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julius-caesar","cicero"], powerLinks:[],
   tags:["caesar","provincial","consul"], sources:["Wikipedia: Lucius Cornelius Balbus (consul)","Cicero, Pro Balbo"]},
  {id:"maecenas", displayName:"Maecenas", fullName:"Gaius Maecenas", alternateNames:[], year:-30, dynasty:"secondTriumvirate",
   role:"Octavian's minister; patron of Vergil and Horace", bio:"Equestrian of Etruscan royal stock who served Octavian as diplomat (he negotiated the pacts of Brundisium 40 and Tarentum 37) and internal security chief, ruling Rome while Octavian campaigned. His literary circle — Vergil, Horace, Propertius, Varius — turned Augustan patronage into golden-age poetry.",
   njclNote:"THE patron: Vergil's Georgics and Horace's Odes exist inside his circle. Prototype of the courtier-minister.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["octavian","vergil","horace"], powerLinks:[],
   tags:["augustus","patron","literature"], sources:["Wikipedia: Gaius Maecenas","Horace; Dio"]},
  {id:"vergil", displayName:"Vergil", fullName:"Publius Vergilius Maro", alternateNames:["Virgil"], year:-19, dynasty:"secondTriumvirate",
   role:"Poet of the Aeneid", bio:"Born near Mantua (70 BC); his Eclogues and Georgics preceded the Aeneid, the epic that fused Rome's foundation legend with Augustan ideology — Aeneas' flight, Lavinium, Alba Longa, and the pageant of Roman heroes. Dying at Brundisium in 19 BC, he ordered the unfinished poem burned; Augustus forbade it.",
   njclNote:"The single most important author for the myth-history material: Aen. 1 = storm/Carthage, 2 = Troy's fall, 4 = Dido, 6 = heroes' parade, 8 = shield/future Rome.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["maecenas","octavian","pollio","horace"], powerLinks:[],
   tags:["literature","aeneid","augustus"], sources:["Wikipedia: Virgil","Suetonius, Life of Vergil"]},
  {id:"horace", displayName:"Horace", fullName:"Quintus Horatius Flaccus", alternateNames:[], year:-35, dynasty:"secondTriumvirate",
   role:"Poet; veteran of Philippi", bio:"Freedman's son from Venusia (65 BC) who fought as a tribune in Brutus' army at Philippi (42) and was pardoned. Taken up by Maecenas, he produced Satires, Epodes, the four books of Odes, Epistles and the Ars Poetica — and Augustus' festival hymn, the Carmen Saeculare (17 BC).",
   njclNote:"Republican-then-Augustan arc: fought FOR the liberators at Philippi, ended as Augustus' laureate — like much of his generation.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["maecenas","brutus","vergil","octavian"], powerLinks:[],
   tags:["literature","philippi","augustus"], sources:["Wikipedia: Horace","Suetonius, Life of Horace"]},
  {id:"livy", displayName:"Livy", fullName:"Titus Livius", alternateNames:["Titus Livius Patavinus"], year:-20, dynasty:"secondTriumvirate",
   role:"Historian; author of Ab Urbe Condita", bio:"Native of Patavium (Padua) who spent his life composing Ab Urbe Condita, 'From the Founding of the City' — 142 books of which 35 survive. Augustus teased him as a 'Pompeian' but sponsored his history; it became the canonical account of Rome's kings and Republic.",
   njclNote:"Certamen's default history book: kings (Bk 1), early Republic (2–5), Samnites (7–10), Punic Wars (21–30). 142 books, 35 survive.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["octavian"], powerLinks:[],
   tags:["historian","literature","abUrbeCondita"], sources:["Wikipedia: Livy","Ab Urbe Condita; Tacitus"]},
  {id:"varro", displayName:"Varro", fullName:"Marcus Terentius Varro", alternateNames:["Varro Reatinus"], year:-50, dynasty:"secondTriumvirate",
   role:"Rome's greatest scholar", bio:"Called 'the most learned of Romans,' Varro (116–27 BC) served Pompey in Spain, was pardoned by Caesar and tasked with a public library, survived Antony's proscription, and wrote some 74 works in ~620 books — De Lingua Latina, Res Rusticae, and the Antiquitates that preserved Roman religion and antiquities.",
   njclNote:"The encyclopedist everyone else quotes: if a Roman custom or god is attested once, it's usually in Varro.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["pompey","julius-caesar"], powerLinks:["mark-antony"],
   tags:["scholar","literature","antiquarian"], sources:["Wikipedia: Marcus Terentius Varro","Augustine; Pliny"]},
  {id:"cornelius-nepos", displayName:"Cornelius Nepos", fullName:"Cornelius Nepos", alternateNames:["Nepos"], year:-40, dynasty:"secondTriumvirate",
   role:"Biographer of great generals", bio:"Cisalpine Gaul and friend of Cicero, Atticus, and Catullus (who dedicated his book to him). His De Viris Illustribus — paired short lives of Romans and foreigners — survives in fragments, including the lives of Hannibal, Cato the Elder, and Atticus.",
   njclNote:"The earliest surviving Latin biographer: his Hannibal and Atticus lives are certamen staples, and Catullus 1 is addressed to him.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["atticus","cicero","catullus"], powerLinks:[],
   tags:["biographer","literature"], sources:["Wikipedia: Cornelius Nepos","De Viris Illustribus"]},
  {id:"caesarion", displayName:"Caesarion", fullName:"Ptolemy XV Caesarion", alternateNames:["Ptolemy XV","Caesarion"], year:-30, dynasty:"secondTriumvirate",
   role:"Son of Caesar and Cleopatra", bio:"Born 47 BC, acknowledged by Cleopatra as Caesar's son and made co-ruler of Egypt (44). After Antony's defeat he was sent to safety but lured back and executed on Octavian's order (30 BC) — as Arius Didymus reportedly warned, 'it is not good to have too many Caesars.'",
   njclNote:"Octavian's coldest act: he spared Antony's and Cleopatra's other children but not the boy with Caesar's blood. Egypt became a province.",
   biologicalLinks:["julius-caesar","cleopatra"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:["octavian"],
   tags:["egypt","caesar","octavian"], sources:["Wikipedia: Caesarion","Plutarch, Antony; Suetonius"]},
  {id:"herod-the-great", displayName:"Herod the Great", fullName:"Herod I, king of Judaea", alternateNames:["Herod I"], year:-37, dynasty:"secondTriumvirate",
   role:"Client king of Judaea", bio:"Idumaean strongman named king of Judaea by the Senate at Antony's urging (40 BC) who took Jerusalem by force in 37 and ruled until 4 BC — switching smoothly from Antony to Octavian after Actium. He rebuilt the Jerusalem Temple magnificently; Matthew's Gospel makes him the villain of the Massacre of the Innocents.",
   njclNote:"Rome's model client king: named by Antony, kept by Octavian — his death (4 BC) is the pivot to direct rule of Judaea (6 AD).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["mark-antony","octavian"], powerLinks:[],
   tags:["clientKing","judaea","east"], sources:["Wikipedia: Herod the Great","Josephus, Antiquities; Matthew 2"]},
]);
